namespace: "elreydetoda"
name: "virtualization"
version: "1.1.4"
readme: "README.md"
authors:
  - "Mihai Criveti (https://twitter.com/crivetimihai)"
  - "Alex R. (https://twitter.com/RonJonArod)"
description: "Virtualization tools - VirtualBox, KVM, VMware, LXD, Docker-CE, Podman, Vagrant, Packer"
license:
  - "MIT"
tags:
  - linux
  - virtualization
  - hypervisor
  - virtualbox
  - kvm
  - vmware
  - docker
  - podman
  - vagrant
  - packer
  - vmtools
  - packaging
  - collection
repository: "https://www.github.com/elreydetoda/ansible_virtualization"
homepage: "https://www.github.com/elreydetoda/ansible_virtualization"
documentation: "https://crivetimihai.github.io/ansible_virtualization/"
issues: "https://www.github.com/elreydetoda/ansible_virtualization/issues"
